version: "3.3"

services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    restart: always
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 5000
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - internal-network

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_pass
      POSTGRES_DB: bank_bd
    networks:
      - internal-network

  account-service:
    build: ./account-service
    container_name: account-service
    restart: always
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_bd
      - SPRING_DATASOURCE_USERNAME=bank_user
      - SPRING_DATASOURCE_PASSWORD=bank_pass
    networks:
      - internal-network

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    restart: always
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_bd
      - SPRING_DATASOURCE_USERNAME=bank_user
      - SPRING_DATASOURCE_PASSWORD=bank_pass
    networks:
      - internal-network

  bff-service:
    build: ./bff-service
    container_name: bff-service
    restart: always
    depends_on:
      - account-service
      - transaction-service
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_bd
      - SPRING_DATASOURCE_USERNAME=bank_user
      - SPRING_DATASOURCE_PASSWORD=bank_pass
    networks:
      - internal-network
    ports:
      - "8080:8080"  # Exponer el BFF en el puerto 8080

networks:
  internal-network:
    driver: bridge
