version: "3.3"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_pass
      POSTGRES_DB: bank_bd
    networks:
      - internal-network

  account-service:
    build: ./account-service
    container_name: account-service
    restart: always
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_bd
      - SPRING_DATASOURCE_USERNAME=bank_user
      - SPRING_DATASOURCE_PASSWORD=bank_pass
    networks:
      - internal-network

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    restart: always
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_bd
      - SPRING_DATASOURCE_USERNAME=bank_user
      - SPRING_DATASOURCE_PASSWORD=bank_pass
    networks:
      - internal-network

  bff-service:
    build: ./bff-service
    container_name: bff-service
    restart: always
    depends_on:
      - account-service
      - transaction-service
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bank_bd
      - SPRING_DATASOURCE_USERNAME=bank_user
      - SPRING_DATASOURCE_PASSWORD=bank_pass
    networks:
      - internal-network
    ports:
      - "8080:8080"  # Exponer el BFF en el puerto 8080

networks:
  internal-network:
    driver: bridge
