spring:
  application:
    name: bff-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "MySuperSecretKeyForJWTWith32Chars!!"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE
    reactor.netty.http.server: TRACE
    org.springframework.web: TRACE